### PR TITLE
resize fix, trayicon, autostart

### LINKED ISSUE #4: Correct opacity value is no checked.
When rulers starts first time, opacity value is not set correctly.

### PR DESCRIPTION
**Pull request by FDIM**
Hi,
I was using miotoolbox for color picker and rulers, but recently I've discovered [instant-eyedropper](http://instant-eyedropper.com/?ref=ie) and found it very useful.
On that note, I started to look for ruler replacement and found your little app and decided to extend it a bit. 

Running it now will add a tray icon and let you do following things:

- single click - shows horizontal ruler
- middle click - shows vertical ruler
- right click - shows context menu

Context menu includes:

- horizontal ruler
- vertical ruler
- autostart option (uses windows registry)
- about - opens your github repo instead of old author details
- exit - there is a mutex lock now, only once instance at the time as ruler won't show up in taskbar.

At the same time #5 is fixed, and resizing will work from any direction - not just S,E,SE.

For future reference, it would be a good idea to remember ruler settings (stay on top, opacity, tooltip), but I am not sure what is the best way to do it - it's either registry or a config file. 
 
Let me know what you think :) 

Edit: also fixes #4 
Edit2: Thanks for @Ishmaeel for resize/drag fix.

### CODE REVIEW

**Comment by FDIM** [comment]
Somehow I've got excited about this and just made 'save as default' functionality :). It will persist 2 rulers settings using existing serialization logic in ruler.cfg file in same directory as executable. Now I can use it in peace :)

**Comment by andrijac** [comment]
Seems like a lot of changes. I'll review it. Thanks :)

**Comment by andrijac** [comment]
**Acceptable fixes:**

>At the same time #5 is fixed, and resizing will work from any direction - not just S,E,SE.

<span/>

> about - opens your github repo instead of old author details


**Cannot accept:**

Any kind of state persistance, this includes configuration and registry enteries. This is small helper app that should not leave traces in system, that can be moved around and copied in mutiple places if needed, that can be started in mutiple instances (more than 2).

- Tray icon
- Registry enteries
- Configuration saving (.cfg file)
- Use tabs, not spaces.
- Don't change output path (check).
- Don't change classes names and files names.
- Don't change existing menu item titles.
- Don't remove stuff from .gitignore

**Comment by FDIM** [comment]
Alright. Then you can close the pull request. I find it much more convenient to create rulers from trayicon instead of launching separate executables, mainly because settings can be persistent.

**Comment by andrijac** [comment]
If you can include changes with resizing, that would be great.
I added to original version "Duplicate" so people imminently duplicate while they work with ruler, rather then fire up again, whether from executable or try icon. Also, I keep ruler in Path always, so I just call it from cmd "ruler".

**Pull request closed without merging**
