### PR TITLE
Add marker on ruler

### PR DESCRIPTION
**Pull request by IsaacMorris1980**
Was able to download the file posted on #63  and copied the code from the file into the ruler for the marker only not the scaling

### CODE REVIEW

**Comment by andrijac** [comment]
I'm on vacation, I'll take a look when I come back, thanks

**Comment by IsaacMorris1980** [comment]
@andrijac   what ever invitation you sent expired my main computer died and it took ahile to get another computer setup sorry i missed it

**Comment by IsaacMorris1980** [comment]
going to re-implement a different way

**Comment by IsaacMorris1980** [comment]
This should implement #57  and  the marker part of #63

**Review by IsaacMorris1980 — COMMENTED** [review]
Not sure why it looks like i replaced entire files

**Pull request merged**
